{
 "title": "Doppler",
 "time": { "from": "now-8d", "to": "now-1d" },
 "panels": [
  {
   "title": "Total Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(cputime) / 3600 AS core_hours FROM jobs WHERE (date BETWEEN $__timeFrom() AND $__timeTo());"
    },
    {
     "rawSql": "SELECT sum(gputime) / 3600 AS gpu_hours FROM gpuinfo WHERE (date BETWEEN $__timeFrom() AND $__timeTo());"
    },
    {
     "rawSql": "SELECT sum(memoryuse) AS mem FROM jobs WHERE (date BETWEEN $__timeFrom() AND $__timeTo());"
    },
    {
     "rawSql": "SELECT sum(tlimituse) / 3600 AS tlimituse FROM jobs WHERE (date BETWEEN $__timeFrom() AND $__timeTo());"
    },
    {
     "rawSql": "SELECT COUNT(*) AS 'active users' FROM (SELECT COUNT(username) FROM jobs WHERE (date BETWEEN $__timeFrom() AND $__timeTo()) GROUP BY username ORDER BY sum(jobsum) DESC) as x;"
    },
    {
     "rawSql": "SELECT COUNT(*) AS 'active accts' FROM (SELECT COUNT(account) FROM jobs WHERE (date BETWEEN $__timeFrom() AND $__timeTo()) GROUP BY account ORDER BY sum(jobsum) DESC) as x;"
    }
   ]
  },
  {
   "title": "Cluster Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(STR_TO_DATE(t1.date, '%Y-%m-%d')) AS time,\n       t1.cpu_eff,\n       t2.gpu_eff,\n       t1.mem_eff,\n       t1.time_eff,\n       ((IFNULL(t1.cpu_eff, 0) + t1.mem_eff + t1.time_eff + IFNULL(t2.gpu_eff, 0)) / (2.0 + IF(ISNULL(t1.cpu_eff), 0, 1) + IF(ISNULL(t2.gpu_eff), 0, 1))) AS total_eff\nFROM (\n     SELECT date,\n            account,\n            SUM(cputime) / SUM(idealcpu) AS cpu_eff,\n            SUM(memoryuse) / SUM(memoryreq) AS mem_eff,\n            SUM(tlimituse) / SUM(tlimitreq) AS time_eff\n     FROM jobs\n     WHERE (date BETWEEN $__timeFrom() AND $__timeTo())\n     GROUP BY date\n     )t1\nLEFT JOIN (\n          SELECT date,\n                 account,\n                 SUM(gputime) / SUM(idealgpu) AS gpu_eff\n          FROM gpuinfo\n          WHERE (date BETWEEN $__timeFrom() AND $__timeTo())\n          GROUP BY date\n          )t2\nON t1.date = t2.date;"
    }
   ]
  },
  {
   "title": "Cluster Efficiency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(cputime) / sum(idealcpu)  AS cpu_eff FROM jobs WHERE (date BETWEEN $__timeFrom() AND $__timeTo());"
    },
    {
     "rawSql": "SELECT sum(gputime) / sum(idealgpu) AS gpu_eff FROM gpuinfo WHERE (date BETWEEN $__timeFrom() AND $__timeTo());"
    },
    {
     "rawSql": "SELECT sum(memoryuse) / sum(memoryreq) AS mem_eff FROM jobs WHERE (date BETWEEN $__timeFrom() AND $__timeTo());"
    },
    {
     "rawSql": "SELECT sum(tlimituse) / sum(tlimitreq) AS time_eff FROM jobs WHERE (date BETWEEN $__timeFrom() AND $__timeTo());"
    },
    {
     "rawSql": "SELECT ((IFNULL(t1.cpu_eff, 0) + t1.mem_eff + t1.time_eff + IFNULL(t2.gpu_eff, 0)) / (2.0 + IF(ISNULL(t1.cpu_eff), 0, 1) + IF(ISNULL(t2.gpu_eff), 0, 1))) AS total_eff\nFROM (\n     SELECT SUM(cputime) / SUM(idealcpu) AS cpu_eff,\n            SUM(memoryuse) / SUM(memoryreq) AS mem_eff,\n            SUM(tlimituse) / SUM(tlimitreq) AS time_eff\n     FROM jobs\n     WHERE (date BETWEEN $__timeFrom() AND $__timeTo())\n     )t1\nINNER JOIN (\n          SELECT SUM(gputime) / SUM(idealgpu) AS gpu_eff\n          FROM gpuinfo\n          WHERE (date BETWEEN $__timeFrom() AND $__timeTo())\n          )t2;"
    }
   ]
  },
  {
   "title": "Account Ranking (All Active Accounts)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT RANK() OVER ( ORDER BY total_eff DESC ) AS rank,\n       t1.account,\n       t1.cpu_eff,\n       t1.mem_eff,\n       t1.time_eff,\n       t2.gpu_eff,\n       ((IFNULL(t1.cpu_eff, 0) + t1.mem_eff + t1.time_eff + IFNULL(t2.gpu_eff, 0)) / (2.0 + IF(ISNULL(t1.cpu_eff), 0, 1) + IF(ISNULL(t2.gpu_eff), 0, 1))) AS total_eff,\n       t1.cpu_hours,\n       t2.gpu_hours\nFROM (\n     SELECT account,\n            SUM(cputime) / SUM(idealcpu) AS cpu_eff,\n            SUM(memoryuse) / SUM(memoryreq) AS mem_eff,\n            SUM(tlimituse) / SUM(tlimitreq) AS time_eff,\n            SUM(cputime) / 3600 AS cpu_hours\n     FROM jobs\n     WHERE (date BETWEEN $__timeFrom() AND $__timeTo())\n     GROUP BY account\n     )t1\nLEFT JOIN (\n          SELECT account,\n                 SUM(gputime) / SUM(idealgpu) AS gpu_eff,\n                 SUM(gputime) / 3600 AS gpu_hours\n          FROM gpuinfo\n          WHERE (date BETWEEN $__timeFrom() AND $__timeTo())\n          GROUP BY account\n          )t2\nON t1.account = t2.account\nORDER BY rank;"
    }
   ]
  },
  {
   "title": "User Ranking (All Active Users)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT RANK() OVER ( ORDER BY total_eff DESC ) AS rank,\n       t1.username,\n       t1.cpu_eff,\n       t1.mem_eff,\n       t1.time_eff,\n       t2.gpu_eff,\n       ((IFNULL(t1.cpu_eff, 0) + t1.mem_eff + t1.time_eff + IFNULL(t2.gpu_eff, 0)) / (2.0 + IF(ISNULL(t1.cpu_eff), 0, 1) + IF(ISNULL(t2.gpu_eff), 0, 1))) AS total_eff,\n       t1.cpu_hours,\n       t2.gpu_hours\nFROM (\n     SELECT username,\n            SUM(cputime) / SUM(idealcpu) AS cpu_eff,\n            SUM(memoryuse) / SUM(memoryreq) AS mem_eff,\n            SUM(tlimituse) / SUM(tlimitreq) AS time_eff,\n            SUM(cputime) AS cpu_hours\n     FROM jobs\n     WHERE (date BETWEEN $__timeFrom() AND $__timeTo())\n     GROUP BY username\n     )t1\nLEFT JOIN (\n          SELECT username,\n                 SUM(gputime) / SUM(idealgpu) AS gpu_eff,\n                 SUM(gputime) AS gpu_hours\n          FROM gpuinfo\n          WHERE (date BETWEEN $__timeFrom() AND $__timeTo())\n          GROUP BY username\n          )t2\nON t1.username = t2.username\nORDER BY rank;"
    }
   ]
  }
 ]
}