{
 "title": "Doppler (User View)",
 "time": { "from": "now-8d", "to": "now-1d" },
 "templating": {
  "list": [
   {
    "name": "user",
    "query": "SELECT DISTINCT username FROM jobs;"
   }
  ]
 },
 "panels": [
  {
   "title": "$user efficiency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(STR_TO_DATE(t1.date, '%Y-%m-%d')) AS time,\n       t1.cpu_eff,\n       t2.gpu_eff,\n       t1.mem_eff,\n       t1.time_eff,\n       ((IFNULL(t1.cpu_eff, 0) + t1.mem_eff + t1.time_eff + IFNULL(t2.gpu_eff, 0)) / (2.0 + IF(ISNULL(t1.cpu_eff), 0, 1) + IF(ISNULL(t2.gpu_eff), 0, 1))) AS total_eff\nFROM (\n     SELECT date,\n            account,\n            SUM(cputime) / SUM(idealcpu) AS cpu_eff,\n            SUM(memoryuse) / SUM(memoryreq) AS mem_eff,\n            SUM(tlimituse) / SUM(tlimitreq) AS time_eff\n     FROM jobs\n     WHERE (date BETWEEN $__timeFrom() AND $__timeTo()) AND\n           username = '$user'\n     GROUP BY date\n     )t1\nLEFT JOIN (\n          SELECT date,\n                 account,\n                 SUM(gputime) / SUM(idealgpu) AS gpu_eff\n          FROM gpuinfo\n          WHERE (date BETWEEN $__timeFrom() AND $__timeTo()) AND\n                username = '$user'\n          GROUP BY date\n          )t2\nON t1.date = t2.date;"
    }
   ]
  },
  {
   "title": "$user average efficiencies",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date,sum(cputime) / sum(idealcpu) AS cpu_eff FROM jobs WHERE (date BETWEEN $__timeFrom() AND $__timeTo()) AND username = '$user';"
    },
    {
     "rawSql": "SELECT date,sum(gputime) / sum(idealgpu) AS gpu_eff FROM gpuinfo WHERE (date BETWEEN $__timeFrom() AND $__timeTo()) AND username = '$user';"
    },
    {
     "rawSql": "SELECT date,sum(memoryuse) / sum(memoryreq) AS mem_eff FROM jobs WHERE (date BETWEEN $__timeFrom() AND $__timeTo()) AND username = '$user';"
    },
    {
     "rawSql": "SELECT date,sum(tlimituse) / sum(tlimitreq) AS time_eff FROM jobs WHERE (date BETWEEN $__timeFrom() AND $__timeTo()) AND username = '$user';"
    },
    {
     "rawSql": "SELECT ((IFNULL(t1.cpu_eff, 0) + t1.mem_eff + t1.time_eff + IFNULL(t2.gpu_eff, 0)) / (2.0 + IF(ISNULL(t1.cpu_eff), 0, 1) + IF(ISNULL(t2.gpu_eff), 0, 1))) AS total_eff\nFROM (\n     SELECT SUM(cputime) / SUM(idealcpu) AS cpu_eff,\n            SUM(memoryuse) / SUM(memoryreq) AS mem_eff,\n            SUM(tlimituse) / SUM(tlimitreq) AS time_eff\n     FROM jobs\n     WHERE (date BETWEEN $__timeFrom() AND $__timeTo()) AND\n           username = '$user'\n     )t1\nINNER JOIN (\n          SELECT SUM(gputime) / SUM(idealgpu) AS gpu_eff\n          FROM gpuinfo\n          WHERE (date BETWEEN $__timeFrom() AND $__timeTo()) AND\n                username = '$user'\n          )t2;"
    }
   ]
  },
  {
   "title": "Account Stats (For each active $user account)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT t1.account,\n       t1.cpu_eff,\n       t1.mem_eff,\n       t1.time_eff,\n       t2.gpu_eff,\n       ((IFNULL(t1.cpu_eff, 0) + t1.mem_eff + t1.time_eff + IFNULL(t2.gpu_eff, 0)) / (2.0 + IF(ISNULL(t1.cpu_eff), 0, 1) + IF(ISNULL(t2.gpu_eff), 0, 1))) AS total_eff,\n       t1.cpu_hours,\n       t2.gpu_hours\nFROM (\n     SELECT account,\n            SUM(cputime) / SUM(idealcpu) AS cpu_eff,\n            SUM(memoryuse) / SUM(memoryreq) AS mem_eff,\n            SUM(tlimituse) / SUM(tlimitreq) AS time_eff,\n            SUM(cputime) / 3600 AS cpu_hours\n     FROM jobs\n     WHERE (date BETWEEN $__timeFrom() AND $__timeTo()) AND\n           username = '$user'\n     GROUP BY account\n     )t1\nLEFT JOIN (\n          SELECT account,\n                 SUM(gputime) / SUM(idealgpu) AS gpu_eff,\n                 SUM(gputime) / 3600 AS gpu_hours\n          FROM gpuinfo\n          WHERE (date BETWEEN $__timeFrom() AND $__timeTo()) AND\n                username = '$user'\n          GROUP BY username\n          )t2\nON t1.account = t2.account;"
    }
   ]
  }
 ]
}